### ISSUE TITLE
Possible enhancements: Search by flight number, include Points searches and don't require intervals

### ISSUE THREAD

**Issue by hoopsbwc34** [wcrasta/SWA-Scraper#36]
So I originally started this due to a user error in entering departure dates, I didn't realize I had to enter the "0" before the single digit month and it was causing me issues.  

But I thought since I can't delete the issue I would offer three enhancements that I coded up tonight once I got it working.  
1) I created an xpath to search for a specific flight number 
2) I added the ability to search based on points
3) I use a script to run this via cron because I've had problems with long running python scripts crashing, so I made the interval optional

If any of these might be useful to others I'd be happy to do a pull request

**Comment by wcrasta** [comment]
Hi @hoopsbwc34, thanks for your post. First of all, I'm glad that this program is working for you and that there's no error. Regarding your enhancements:

1. I'm not sure I understand the intent of this feature. Why is searching for a flight useful? Can you give me an example of how a user would use this?
2. Same as 1. What does it mean to search on points?
3. Fair point. I'd accept a PR making interval optional. 

By the way, I hope it doesn't sound like I'm discouraging your enhancements. I'm just trying to understand the intent a little more. Thanks for your interest!

**Comment by hoopsbwc34** [comment]
No worries. I probably use this program different than others, so that's why I made these changes in my version.  It would be nice to merge them so I don't have to recode them like I had to with this major version change, but it's not a big deal either way.  

1) If you only want to fly a specific time (ie one flight) and want to see when that flight's price drops you could use the flight # tag. 
2) I book most of my flights using my SW points, so I want to know when the point value changes below a threshold.  For example, flight A is 10000 points and I want to know if it drops below 9000 points.

**Comment by jgoggan** [comment]
I would totally use these features!

To answer question 1: You would search for a specific flight because maybe you can only leave at a certain time.  Telling me the cheapest flight the entire DAY doesn't matter much if that is some red-eye flight that arrives after midnight the next day (which is very common for my airport).  Or, I often have to work before I leave -- so I'll only want to watch, for example, the 2pm flight for a specific day -- because it doesn't matter to me if the 9am flight is cheaper because I can't do that flight.  Often, only a specific flight makes sense to watch for me.

As for question 2...  You can pay using cash or points.  But, it isn't a direct ratio any more.  You can't just go "Ok, that is $250 flight, so it would be X points."  And, when I have points, I'm often not willing to pay cash for a flight.  Often, flying a different airline -- where I have to pay cash -- is cheaper.  So, I'll only be interested in doing the SWA flight if it is under a certain number of points because that is the only way I'm going to book the flight.

So, for me, both of these features are great options that I would totally use.  I would hope that you merge them in -- so that people CAN use them if they want, but certainly don't have to, of course.

Nice work, hoopsbwc34!  I would totally use your version and hope that it gets merged in as optional!

**Comment by wcrasta** [comment]
Got it, thanks for the clarity. I'll work directly with @hoopsbwc34 (via e-mail) to discuss integrating these features into the project.
